apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: frontend
  labels:
    app: web
    app.kubernetes.io/part-of: demo
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot:v0.15
    imagePullPolicy: IfNotPresent
    command: ["sleep", "infinity"]
