apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: frontend
  labels:
    app: web
    app.kubernetes.io/part-of: demo
spec:
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
