apiVersion: v1
kind: Pod
metadata:
  name: api
  namespace: backend
  labels:
    app: api
    app.kubernetes.io/part-of: demo
spec:
  containers:
    - name: httpbin
      image: mccutchen/go-httpbin:2.20.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
